name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Give execute permission to the script
      run: chmod +x ./script/run_tests.sh

    - name: Run tests
      run: ./script/run_tests.sh  # Execute the script
